### ISSUE TITLE
Is Python 3.6 a requirement?

### ISSUE THREAD

**Issue by neich** [Techcable/DiffUtils#1]
Hi,

I'm trying to install this library in Ubuntu 16.04 and there are errors with Python 3.5. Specifically with Literal String Interpolation. Is that a requirement for DiffUtils ? Is there a workaround to use it with Python 3.5 ?

Thanks

**Comment by Techcable** [comment]
Yeah, I'll go make it optional right now ;)

**Comment by neich** [comment]
Great! Thanks!

**Comment by Techcable** [comment]
Just a second, I have to correctly setup travis-ci before I can test it and release it to pypy. Just open a new issue if there are any more compatibility problems once I release the new version.
